# This file should contain everything to configure the workflow on a global scale.
basecalled_dir: "/mnt/md0/UMI16S/zymock/pass"
results_dir: "/mnt/md0/UMI16S/zymock_res_subsampled"
database_dir: "/mnt/md0/Database/Kamp"
guppy: "resources/ont-guppy/bin" # guppy bin

threads:
    normal: 2 # short request for threads
    large: 6 # threads dependent e.g., canu
# demultiplex with guppy
barcode_kits: "SQK16S-GXO"

# Pooling samples for denoise [True|False]
pooling: True
# mode for cluster consensus [isONclustCon|isONcorCon]
# isONclustCon: NGSpeciesID on kmer clusters (divergent similarity)
# isONcorCon: isONclust followed by isONcorrect and IsoCon (close similarity)
clustCon: isONclustCon
# Subsampling raw reads if with inadequate memory
subsample: TRUE

seqkit:
  min-qual: 7
  min-len: 500
  max-len: -1
  # subsampling params
  p: 0.9 # subsampling portion, upper it if with uneven library [float]
  n: 20000 # subsampling number [int]

# umi extraction with seqkit and cutadapt
umi_loc: 100 # robust location of umi, i.e. within 100 bp in the start/end of the sequence
umi_len: 15 # base length of umi design
umi_flexible: 2 # flexible base length for umi
max_err: 0.2 # cutadapt -e, high error tolerance for nanopore 
min_overlap: 5 # cutadapt -O, recommened: 0.25*length
# linker and primer for umi extraction
flinker: "GTCTCGTGGGCTCGG"
# order matters
fprimer:
  27Fa: "AGAGTTTGATYMTGGCTYAG"
  27Fb: "AGGGTTCGATTCTGGCTCAG"
  338Fa: "ACWCCTACGGGWGGCAGCAG"
  338Fb: "GACTCCTACGGGAGGCWGCAG"

rlinker: "GTCTCGTGGGCTCGG"
rprimer: 
  1540R: "TACGGYTACCTTGTTACGACT"
  1391R: "GACGGGCGGTGTGTRCA"
# umi cluster
umi_id: 0.9

# Quality control
cutadapt:
  max_errors: 0.3
  min_overlap: 5
  minimum-length: 1

# kmer cluster
kmer_size: 5
# umap reduction and hdbscan cluster
umap:
  n_neighbors: 15 # Increase this for global structure
  min_dist: 0.1 # Lower this to increase density for clustering (0.0, 0.99)
  n_components: 2
hdbscan:
  min_cluster_size: 50 # Define the smallest size to cluster
  min_samples: 50 # Increase this for more conservative clustering - more points as noise
  epsilon: 0 # Lower this for more micro-clusters

NGSpeciesID:
  racon_iter: 2

minimap:
  x: map-ont
  index_size: 4G 

samtools:
  m: 3G
  
medaka:
  m: r941_min_fast_g507

mmseqs:
  min-seq-id: 1
  c: 1 # the fraction of aligned residues
  dbname: NT # predefined database name in `mmseqs databases`
  lca-mode: 3 #LCA Mode 1: single search LCA , 2/3: approximate 2bLCA, 4: top hit [3]