# This file should contain everything to configure the workflow on a global scale.
basecalled_dir: "data/run"
results_dir: "results"
guppy_dir: "resources/ont-guppy/bin"
threads_taxa: 8
threads_demultiplex: 2
# linker and primer for umi extraction
flinker: "GTCTCGTGGGCTCGG"
fprimer:
  338Fa: "ACWCCTACGGGWGGCAGCAG"
  338Fb: "GACTCCTACGGGAGGCWGCAG"
  27Fa: "AGAGTTTGATYMTGGCTYAG"
  27Fb: "AGGGTTCGATTCTGGCTCAG"

rlinker: "GTCTCGTGGGCTCGG"
rprimer: 
  1391R: "GACGGGCGGTGTGTRCA"
  1540R: "TACGGYTACCTTGTTACGACT"
