# This file should contain everything to configure the workflow on a global scale.
basecalled_dir: "/mnt/md0/UMI16S/zymock/pass"
results_dir: "/mnt/md0/UMI16S/zymock_res"
database_dir: "/mnt/md0/Database/NanoAmp"
guppy: "resources/ont-guppy/bin" # guppy bin

threads:
    normal: 2 # short request for threads
    large: 6 # threads dependent e.g., canu
# demultiplex with guppy
barcode_kits: "SQK16S-GXO"

# Pooling samples for denoise [True|False]
pooling: True

# umi extraction with seqkit and cutadapt
umi_loc: 100 # robust location of umi, i.e. within 100 bp in the start/end of the sequence
umi_len: 15 # base length of umi design
umi_flexible: 2 # flexible base length for umi
max_err: 0.2 # cutadapt -e 
min_overlap: 9 # cutadapt -O, recommened: 0.25*length(linked_adapter)
# linker and primer for umi extraction
flinker: "GTCTCGTGGGCTCGG"
fprimer:
  338Fa: "ACWCCTACGGGWGGCAGCAG"
  338Fb: "GACTCCTACGGGAGGCWGCAG"
  27Fa: "AGAGTTTGATYMTGGCTYAG"
  27Fb: "AGGGTTCGATTCTGGCTCAG"

rlinker: "GTCTCGTGGGCTCGG"
rprimer: 
  1391R: "GACGGGCGGTGTGTRCA"
  1540R: "TACGGYTACCTTGTTACGACT"
# umi cluster
umi_id: 0.9

# Quality control
seqkit:
  min-qual: 7
  min-len: 50
  max-len: -1

# kmer cluster
kmer_size: 5
# umap reduction and hdbscan cluster
umap:
  n_neighbors: 100 # Increase this for global structure
  min_dist: 0.1 # Lower this to increase density for clustering (0.0, 0.99)
  n_components: 2
hdbscan:
  min_cluster_size: 50 # Define the smallest size to cluster
  min_samples: 50 # Increase this for more conservative clustering - more points as noise
  epsilon: 0 # Lower this for more micro-clusters

NGSpeciesID:
  racon_iter: 2

minimap:
  x: map-ont
  index_size: 4G 

samtools:
  m: 3G
  
medaka:
  m: r941_min_fast_g507