# This file should contain everything to configure the workflow on a global scale.
basecalled_dir: "data/run"
results_dir: "results"
guppy: "resources/ont-guppy/bin" # guppy bin
threads_taxa: 8
threads_demultiplex: 2
# demultiplex with guppy
barcode_kits: "SQK16S-GXO"
use_cuda: FALSE 
# linker and primer for umi extraction
umi_loc: 100 # robust location of umi, i.e. within 100 bp in the start/end of the sequence
flinker: "GTCTCGTGGGCTCGG"
fprimer:
  338Fa: "ACWCCTACGGGWGGCAGCAG"
  338Fb: "GACTCCTACGGGAGGCWGCAG"
  27Fa: "AGAGTTTGATYMTGGCTYAG"
  27Fb: "AGGGTTCGATTCTGGCTCAG"

rlinker: "GTCTCGTGGGCTCGG"
rprimer: 
  1391R: "GACGGGCGGTGTGTRCA"
  1540R: "TACGGYTACCTTGTTACGACT"
