# This file should contain everything to configure the workflow on a global scale.
basecalled_dir: "/mnt/md0/UMI16S/zymock/pass"
results_dir: "/mnt/md0/UMI16S/zymock_res_subsampled"
database_dir: "/mnt/md0/Database/Kamp"
guppy: "resources/ont-guppy/bin" # guppy bin

threads:
    normal: 2 # short request for threads
    large: 6 # threads dependent e.g., canu

# Pooling samples for denoise [True|False]
pooling: True

##############################################################
# Demultiplex with guppy
barcode_kits: "SQK16S-GXO"
##############################################################
# Quality control
# Subsampling raw reads if with inadequate memory
subsample: TRUE

seqkit:
  min-qual: 7
  min-len: 500
  max-len: -1
  # subsampling params
  p: 0.9 # subsampling portion, upper it if with uneven library [float]
  n: 5000 # subsampling number [int]

# order matters
fprimer:
  27Fa: "AGAGTTTGATYMTGGCTYAG"
  27Fb: "AGGGTTCGATTCTGGCTCAG"
  338Fa: "ACWCCTACGGGWGGCAGCAG"
  338Fb: "GACTCCTACGGGAGGCWGCAG"

rprimer: 
  1540R: "TACGGYTACCTTGTTACGACT"
  1391R: "GACGGGCGGTGTGTRCA"

cutadapt:
  max_errors: 0.3
  min_overlap: 5
  minimum-length: 1

##############################################################
# kmer binning
kmer_size: 5
# umap reduction and hdbscan cluster
umap:
  n_neighbors: 15 # Increase this for global structure
  min_dist: 0.1 # Lower this to increase density for clustering (0.0, 0.99)
  n_components: 2
hdbscan:
  min_cluster_size: 10 # Define the smallest size to cluster
  min_samples: 10 # Increase this for more conservative clustering - more points as noise
  epsilon: 0 # Lower this for more micro-clusters

##############################################################
# cluster within kmer bins
# mode for cluster consensus [ClustCon|isONclustCon|isONcorCon]
# ClustCon: cluster based on pairwise alignment with minimap2 [orignal method in https://genome.cshlp.org/content/30/3/437]
# isONclustCon: NGSpeciesID on kmer clusters (divergent similarity)
# isONcorCon: isONclust followed by isONcorrect and IsoCon (close similarity)
cluster:
  - clustCon # the first for the final kOTUs
  - isONclustCon
  - isONcorCon

clustCon:
  min_score_frac: 0.8
  min_reads: 5
  max_recursion: -1 # set to non-zero value to override python's max recursion depth

racon:
  iter: 2
  m: 8
  x: -6
  g: -8
  w: 500
  
medaka:
  m: r941_min_hac_g507

NGSpeciesID:
  racon_iter: 2
  abundance_ratio: 0.8 
  # Determine the final cluster size together with min_cluster_size in kmerBin
  # Tunn it to discard small clusters, which may yield error in polishment;
  # E.g., To keep cluster > 8 under min kmerBin > 10, take 0.8 (8/10) for abundance_ratio.

minimap:
  x: map-ont
  index_size: 4G 

samtools:
  m: 3G

##############################################################
# Taxonomy assignment
classifier:
  - kraken2 # the first to be final taxonomy
  - mmseqs2

mmseqs:
  min-seq-id: 1
  c: 1 # the fraction of aligned residues
  taxdb: SILVA # predefined taxonomy database name in `mmseqs databases`; The provided NT database do not have taxonomy info yet.
  # make a custom seqTaxDB using local blast databases;
  #blastdb_ftp: "ftp://ftp.ncbi.nlm.nih.gov/blast/db/refseq_rna.??.tar.gz"
  blastdb_alias: "refseq_rna" # alias for blast database; leave this as empty string [""] if you want to use the default database by mmseqs2
  lca-mode: 3 #LCA Mode 1: single search LCA , 2/3: approximate 2bLCA, 4: top hit [3]

kraken2:
  buildb_cmd: "--standard"
  classify_cmd: "--confidence 0.1"

##############################################################
# Build a de novo phylogenetic tree
# trim possible primers on representative sequences for multi-primer PCR
fprimer_max:
  338Fa: "ACWCCTACGGGWGGCAGCAG"
  338Fb: "GACTCCTACGGGAGGCWGCAG"
rprimer_min:
  1391R: "GACGGGCGGTGTGTRCA"

phylogen:
  - FastTree # the first to be final taxonomy; You can enable the other two, which are more time consuming.
  #- IQ-TREE
  #- RAxML

q2-phylogen:
  # supplementary parameters for q2_phylogen pipeline `align-to-tree-mafft-{fasttree, iqtree, raxml}`
  # https://docs.qiime2.org/2021.11/plugins/available/phylogeny/
  fasttree: ""
  iqtree: ""
  raxml: ""

##############################################################
# umi setttings
# umi extraction with seqkit and cutadapt
umi_loc: 100 # robust location of umi, i.e. within 100 bp in the start/end of the sequence
umi_len: 15 # base length of umi design
umi_flexible: 2 # flexible base length for umi
max_err: 0.2 # cutadapt -e, high error tolerance for nanopore 
min_overlap: 5 # cutadapt -O, recommened: 0.25*length
# linker and primer for umi extraction
flinker: "GTCTCGTGGGCTCGG"
rlinker: "GTCTCGTGGGCTCGG"
# umi cluster
umi_id: 0.9