# This file should contain everything to configure the workflow on a global scale.
basecalled_dir: "data/run"
results_dir: "results"
#results_dir: "results_deep"
guppy: "resources/ont-guppy/bin" # guppy bin
threads:
    normal: 2 # short request for threads
    large: 8 # threads dependent e.g., canu
# demultiplex with guppy
barcode_kits: "SQK16S-GXO"
use_cuda: FALSE 

# umi extraction with seqkit and cutadapt
umi_loc: 100 # robust location of umi, i.e. within 100 bp in the start/end of the sequence
umi_len: 15 # base length of umi design
umi_flexible: 2 # flexible base length for umi
max_err: 0.2 # cutadapt -e 
min_overlap: 9 # cutadapt -O, recommened: 0.25*length(linked_adapter)
# linker and primer for umi extraction
flinker: "GTCTCGTGGGCTCGG"
fprimer:
  338Fa: "ACWCCTACGGGWGGCAGCAG"
  338Fb: "GACTCCTACGGGAGGCWGCAG"
  27Fa: "AGAGTTTGATYMTGGCTYAG"
  27Fb: "AGGGTTCGATTCTGGCTCAG"

rlinker: "GTCTCGTGGGCTCGG"
rprimer: 
  1391R: "GACGGGCGGTGTGTRCA"
  1540R: "TACGGYTACCTTGTTACGACT"
# umi cluster
umi_id: 0.9

# kmer cluster
kmer_size: 5
# umap reduction and hdbscan cluster
hdbscan_size: 50
hdbscan_epsilon: 0.5

# read correction
# canu
amp_size: 1.2k

# drep
pa: 0.9
sa: 0.99
S_algorithm: ANlmf
nc: 0.5
minl: 1000
clusterAlg: single