name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Testing:
    runs-on: ubuntu-latest
    needs: Formatting
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # we need tags for versioneer to work

      - name: Setup LACA environment
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          conda config --set channel_priority flexible
          wget -O Mambaforge.sh https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh --quiet
          bash Mambaforge.sh -b -p "${HOME}/conda"
          source "${HOME}/conda/etc/profile.d/conda.sh"
          source "${HOME}/conda/etc/profile.d/mamba.sh"
          # ensure that mamba is happy to write into the cache
          sudo chown -R runner:docker /usr/share/miniconda/pkgs/cache
          mamba env create -q --name laca --file env.yaml
      
      - name: Install Kamp
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate laca
          pip install --editable .
          laca -h
          laca init -h
          laca run -h

      - name: Dry-run LACA
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate laca
          laca init -b laca/workflow/resources/data -d test/Database -w test
          laca run all -w test -n 

      
           